"""Python mass spectrometry imaging tools inspired by Cardinal."""

from pycardinal.core import (
    MassDataFrame,
    MSImagingArrays,
    MSImagingExperiment,
    PositionDataFrame,
    ProcessingStep,
    SpectraArrays,
    SpectralImagingArrays,
    SpectralImagingData,
    SpectralImagingExperiment,
    XDataFrame,
    XDFrame,
    add_processing,
    process,
    reset,
)
from pycardinal.features import (
    colocalized,
    features,
    pixels,
    slice_image,
    subset,
    subset_features,
    subset_pixels,
)
from pycardinal.io import (
    convert_arrays_to_experiment,
    convert_experiment_to_arrays,
    read_analyze,
    read_imzml,
    read_msi_data,
    write_analyze,
    write_imzml,
    write_msi_data,
)
from pycardinal.plotting import image_model, plot_image, plot_model, plot_spectra
from pycardinal.processing import (
    bin_spectra,
    estimate_domain,
    estimate_reference_mz,
    estimate_reference_peaks,
    normalize,
    peak_align,
    peak_pick,
    peak_process,
    recalibrate,
    reduce_baseline,
    smooth,
)
from pycardinal.roi import make_factor, select_roi
from pycardinal.simulate import (
    add_shape,
    preset_image_def,
    simulate_image,
    simulate_spectra,
)
from pycardinal.spatial import find_neighbors, spatial_dists, spatial_weights
from pycardinal.stats import (
    NMF,
    OPLS,
    PCA,
    PLS,
    contrast_test,
    cross_validate,
    means_test,
    segmentation_test,
    spatial_dgmm,
    spatial_fastmap,
    spatial_kmeans,
    spatial_shrunken_centroids,
    top_features,
)
from pycardinal.summarize import (
    col_stats,
    row_stats,
    summarize_features,
    summarize_pixels,
)

__version__ = "0.1.0"

__all__ = [
    "MSImagingArrays",
    "MSImagingExperiment",
    "MassDataFrame",
    "NMF",
    "OPLS",
    "PCA",
    "PLS",
    "PositionDataFrame",
    "ProcessingStep",
    "SpectraArrays",
    "SpectralImagingArrays",
    "SpectralImagingData",
    "SpectralImagingExperiment",
    "XDFrame",
    "XDataFrame",
    "__version__",
    "add_processing",
    "add_shape",
    "bin_spectra",
    "convert_arrays_to_experiment",
    "convert_experiment_to_arrays",
    "cross_validate",
    "contrast_test",
    "colocalized",
    "col_stats",
    "estimate_domain",
    "estimate_reference_mz",
    "estimate_reference_peaks",
    "features",
    "find_neighbors",
    "image_model",
    "make_factor",
    "pixels",
    "process",
    "peak_align",
    "peak_pick",
    "peak_process",
    "plot_image",
    "plot_model",
    "plot_spectra",
    "preset_image_def",
    "normalize",
    "means_test",
    "read_analyze",
    "read_imzml",
    "read_msi_data",
    "recalibrate",
    "reduce_baseline",
    "row_stats",
    "reset",
    "simulate_image",
    "simulate_spectra",
    "smooth",
    "select_roi",
    "slice_image",
    "spatial_dists",
    "spatial_dgmm",
    "spatial_fastmap",
    "spatial_kmeans",
    "spatial_shrunken_centroids",
    "segmentation_test",
    "spatial_weights",
    "subset",
    "subset_features",
    "subset_pixels",
    "summarize_features",
    "summarize_pixels",
    "top_features",
    "write_analyze",
    "write_imzml",
    "write_msi_data",
]
